spring.datasource.url=jdbc:mysql://localhost:3306/sangam_db
spring.datasource.username=root
spring.datasource.password=Sahul@54321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# JWT Configuration
jwt.secret=SanGamSuperSecretKeyForJWTAuthentication2026SecureKey123456789
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=first001123456789@gmail.com
spring.mail.password=ontn ilof uynv kgxu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
